FROM debian:11-slim

# 環境設定
ENV LANG ja_JP.UTF-8

RUN apt update \
    && apt install nginx -y \
    && cp /usr/share/zoneinfo/Japan /etc/localtime
COPY ./conf/default.conf /etc/nginx/conf.d/default.conf

# プロセス起動
ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]